accounts/urls.py
from django.conf.urls import url
from . import views

app_name="accounts"

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/edit', views.edit_profile, name='edit_profile'),
    url(r'^profile/', views.profile_view, name='profile'),
    url(r'^password/$', views.change_password, name='change_password'),

]

friends/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = "friends"

urlpatterns = [

    url(r'^friends/$', views.friends_page, name='friends_page'),
    url(r'^friends/(?P<friend_id>\d+)$', views.view_friend, name='view_friend'),
    url(r'^noneshared$', views.noneshared, name='noneshared'),
    url(r'^remove_friend/(?P<friend_pk>\d+)$', views.remove_friend, name='remove_friend'),
    url(r'^search_friend$', views.search_friend, name='search_friend'),

    path('ajax/get_users_by_names/', views.get_users_by_names, name='get_users_by_names'),
    path('ajax/send_friend_request/', views.send_friend_request, name='send_friend_request'),
    path('ajax/respond_friend_request/', views.respond_friend_request, name='respond_friend_request'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('stickynote.urls')), #redirect every url to the homepage
    path('', include('accounts.urls')),
    path('', include('friends.urls')),

]

stickynote/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns #REST API

app_name = "stickynote"

urlpatterns = [
    path('', views.page_load, name='page_load'),
    path('set_sorting_pref_to_title', views.set_sorting_pref_to_title, name='set_sorting_pref_to_title'),
    path('set_sorting_pref_to_edited', views.set_sorting_pref_to_edited, name='set_sorting_pref_to_edited'),
    path('set_sorting_pref_to_created', views.set_sorting_pref_to_created, name='set_sorting_pref_to_created'),

    #TODO: OLD (to be removed probably)
    #path('ajax/retrieve_sticky_colours/', views.retrieve_sticky_colours, name='retrieve_sticky_colours'),
    #path('ajax/retrieve_current_user_data/', views.retrieve_current_user_data, name='retrieve_current_user_data'),
    #path('ajax/create_stickies/', views.create_stickies, name='create_stickies'),

    #UPDATED:
    path('ajax/get_sticky_by_id/', views.get_sticky_by_id, name='get_sticky_by_id'),
    path('ajax/set_or_create_sticky_by_id/', views.set_or_create_sticky_by_id, name='set_or_create_sticky_by_id'),
    path('ajax/delete_sticky_by_id/', views.delete_sticky_by_id, name='delete_sticky_by_id'),

    path('ajax/get_colour_by_id/', views.get_colour_by_id, name='get_colour_by_id'),
    path('ajax/get_random_colour/', views.get_random_colour, name='get_random_colour'),

    path('ajax/get_group_by_id/', views.get_group_by_id, name='get_group_by_id'),
    path('ajax/set_or_create_group_by_id/', views.set_or_create_group_by_id, name='set_or_create_group_by_id'),
    path('ajax/delete_group_by_id/', views.delete_group_by_id, name='delete_group_by_id'),

    path('ajax/user_is_authenticated/', views.user_is_authenticated, name='user_is_authenticated'),
    path('ajax/user_login/', views.user_login, name='user_login'),
    path('ajax/user_logout/', views.user_logout, name='user_logout'),

    #REST API
    path('stickies/', views.StickynoteList.as_view()),
    path('stickies/<int:id>/', views.StickynoteDetails.as_view()),
    path('stickies/user/<int:author_id>/', views.StickynoteAuthorList.as_view()),
    path('colours/', views.ColourList.as_view()),
    path('colours/<int:id>/', views.ColourDetails.as_view()),
    path('users/', views.UserList.as_view()),
    path('users/<int:id>', views.UserDetails.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

stickynote/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

#to save user preference of sorting stickies
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

#Stickynote entry (yes, most of this is unused (or not displayed to the user), though it could be used in A3)
class Stickynote(models.Model):
    #1-to-many relation with a Group (which has an author field), so it's not neccesary here
    '''
    author = models.ForeignKey(
            'auth.User',
            on_delete=models.CASCADE,
            )
    '''
    title = models.CharField(max_length=200)
    contents = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    last_edit_date = models.DateTimeField(
            blank=True, null=True, default=timezone.now)
    colour = models.ForeignKey(
            'Colour',
            on_delete=models.CASCADE,
            )
    group = models.ForeignKey(
            'Group',
            on_delete=models.CASCADE,
            default = 1,
    )
    shared = models.BooleanField()

    def create(self):
        self.created_date = timezone.now()
        self.save()

    def save_edits(self):
        self.last_edit_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

#Colour entry
class Colour(models.Model):
    name = models.CharField(max_length=20)
    r = models.IntegerField(
            default=0,
            validators=[MaxValueValidator(255), MinValueValidator(0)],
    )
    g = models.IntegerField(
            default=0,
            validators=[MaxValueValidator(255), MinValueValidator(0)],
    )
    b = models.IntegerField(
            default=0,
            validators=[MaxValueValidator(255), MinValueValidator(0)],
    )
    a = models.IntegerField(
            default=255,
            validators=[MaxValueValidator(255), MinValueValidator(0)],
    )
    filename = models.CharField(
            default = "stickynote_yellow.png", #files must be locaeted in STATIC/Images/
            max_length = 40,
    )

    def __str__(self):
        return self.name

#Stickynote Group Entry
class Group(models.Model):
    author = models.ForeignKey(
            'auth.User',
            on_delete=models.CASCADE,
            )
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField( #Creation Date
            default=timezone.now)
    last_edit_date = models.DateTimeField( #Last date something was added/removed from this group
            blank=True, null=True, default=timezone.now)
    shared = models.BooleanField()
    cannotBeDeleted = models.BooleanField(default=False)

    def create(self):
        self.created_date = timezone.now()
        self.save()

    def save_edits(self):
        self.last_edit_date = timezone.now()
        self.save()

    def __str__(self):
        return (self.title + " (" + self.author.username + ")")


#to save user preference of sorting stickies
class SortingPreference(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sorting_pref = models.CharField(max_length=30, default="TITLE")

@receiver(post_save, sender=User)
def create_sorting_pref(sender, instance, created, **kwargs):
    if created:
        SortingPreference.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_sorting_pref(sender, instance, **kwargs):
    instance.sortingpreference.save()

stickynote/views.py
from django.contrib.auth.models import User #the user DB table
from .models import Stickynote, Colour, Group, SortingPreference #DB tables
from friends.models import Friend, Collaborator, FriendRequest #DB tables
from django.utils import timezone #timezone-data

from .utility_functions import UsersAreFriends, CanEditStickynote, CanOpenStickynote, GetRandomColour #utility functions

from django.db.models import Count    #Count
from django.shortcuts import render, redirect #rendering
from django.db.models.functions import Lower #to transform to lowercase in a .filter


from random import randint #random number generator
from django.http import JsonResponse #for AJAX requessts
from django.http import HttpResponseRedirect #redirection for POST-requests
from django.contrib.auth import authenticate, login, logout #authenticate, login, and logout users
from django.contrib.auth.decorators import login_required # to require users to log in

import json #for decoding JSON strings

#REST API:
from django.shortcuts import get_object_or_404 #Nice responses
from rest_framework.views import APIView #Lets normal view return API data
from rest_framework.response import Response #Handles JSON,... responses
from rest_framework import status
from .serializers import ColourSerializer, StickynoteSerializer, UserSerializer
from rest_framework import permissions #User permissions (I.e. extra admin priviliges)

#Initial page load
@login_required
def page_load(request):
    stickies = [];
    groups = [];
    colours = [];
    sp = SortingPreference.objects.get(user=request.user)

    iGroupHeaderColourModifier = 0.75;

    if request.user.is_authenticated:
        print('!!!!!!!!!!!!!!!!NEW PAGE LOAD!!!!!!!!!!!!!!!!!!!')
        print(sp.sorting_pref)
        if sp.sorting_pref == "TITLE":
            stickies = Stickynote.objects.filter(group_id__author_id=request.user.id).order_by(Lower('title'));
            print(stickies)
            groups = Group.objects.filter(author_id=request.user.id).order_by('-cannotBeDeleted', Lower('title'));

        elif sp.sorting_pref == "DATE_CREATED":
            stickies = Stickynote.objects.filter(group_id__author_id=request.user.id).order_by('created_date');
            print(stickies)
            groups = Group.objects.filter(author_id=request.user.id).order_by('-cannotBeDeleted', '-created_date');

        elif sp.sorting_pref == "DATE_EDITED":
            stickies = Stickynote.objects.filter(group_id__author_id=request.user.id).order_by('-last_edit_date');
            print(stickies)
            groups = Group.objects.filter(author_id=request.user.id).order_by('-cannotBeDeleted', '-last_edit_date');

        #TODO: remove the if and change the first elif to if. This will have the same functionality.
        else:
            stickies = Stickynote.objects.filter(group_id__author_id=request.user.id).order_by(Lower('title'));
            print(stickies)
            groups = Group.objects.filter(author_id=request.user.id).order_by('-cannotBeDeleted', Lower('title'));

        #Get&Set the colour that most stickies in a group have.
        for group in groups:
            groupStickies = Stickynote.objects.filter(group_id=group.id);
            majorityColour = groupStickies.values("colour_id").annotate(Count("id")).order_by('-id__count');
            majorityColour = majorityColour[0] if majorityColour.count() > 0 else {'colour_id': GetRandomColour().id,'id__count': 0};

            #majorityColour = Colour.objects.get(id=majorityColour.colour_id);
            majorityColour['r'] = round(Colour.objects.get(id=majorityColour['colour_id']).r*iGroupHeaderColourModifier);
            majorityColour['g'] = round(Colour.objects.get(id=majorityColour['colour_id']).b*iGroupHeaderColourModifier);
            majorityColour['b'] = round(Colour.objects.get(id=majorityColour['colour_id']).g*iGroupHeaderColourModifier);
            majorityColour['a'] = Colour.objects.get(id=majorityColour['colour_id']).a;
            majorityColour['colour'] = Colour.objects.get(id=majorityColour['colour_id']);
            group.majorityColour = majorityColour;
        print(groups)
        colours = Colour.objects.all().order_by('name');
        print(colours)
    return render(request, 'stickynote/index.html', {'stickies': stickies, 'groups': groups, 'colours': colours, 'author_id': request.user.id})

#Gets the data of a stickynote with the given ID.
#Returns an error if no such stickynote exists
def get_sticky_by_id(request):
    if request.user.is_authenticated:
        iStickyID = request.GET.get('iStickyID',None)
        #Sticky must exist and only the author of the sticky can retrieve it
        if iStickyID == None or not CanOpenStickynote(iStickyID, request.user.id):
            return JsonResponse({'status':'false','message':"ERROR: Invalid StickynoteID passed or access denied"}, status=404)
        pSticky = Stickynote.objects.get(id=iStickyID);

        data = {
            'title':            pSticky.title,
            'contents':         pSticky.contents,
            'created_date':     pSticky.created_date,
            'last_edit_date':   pSticky.last_edit_date,
            'shared':           pSticky.shared,
            'colour_id':        pSticky.colour_id,
            'group_id':         pSticky.group_id,
            'group_is_shared':  Group.objects.get(id=pSticky.group_id).shared if Group.objects.filter(id=pSticky.group_id).exists() else False,
            'can_edit':         CanEditStickynote(iStickyID, request.user.id),
        }
        return JsonResponse(data)
    return JsonResponse({'status':'false','message':"ERROR: Not Logged in, so nothing to retrieve"}, status=401)

#Gets the data of a Colour with the given ID.
#Returns an error if no such colour exists
def get_colour_by_id(request):
    iColourID = request.GET.get('iColourID',None)
    if iColourID == None or not Colour.objects.filter(id=iColourID).exists():
        return JsonResponse({'status':'false','message':"ERROR: Invalid ColourID passed"}, status=404)

    pColour = Colour.objects.get(id=iColourID);

    data = {
        'name':     pColour.name,
        'r':        pColour.r,
        'g':        pColour.g,
        'b':        pColour.b,
        'a':        pColour.a,
        'filename': pColour.filename,
    }
    return JsonResponse(data)

#
#
def set_or_create_sticky_by_id(request, *args, **kwargs):
    #Must be logged in (otherwise there's nowhere to save to)
    if request.user.is_authenticated:
        sTitle = request.POST.get('title', '');
        sContents = request.POST.get('contents', '');
        iColour = request.POST.get('colour', -1);
        iColour = Colour.objects.get(id=iColour).id if Colour.objects.filter(id=iColour).exists() else Colour.objects.order_by('id')[0].id

        iGroup = request.POST.get('group', -1);
        iGroup = Group.objects.get(id=iGroup).id if Group.objects.filter(id=iGroup).exists() else Group.objects.filter(cannotBeDeleted=True,author_id=request.user.id).order_by('id')[0].id
        bShared = request.POST.get('shared', False) == 'true';

        iID = request.POST.get('id', -1)
        if Stickynote.objects.filter(id=iID).exists():
            #Already Exists: so we update it
            pSticky = Stickynote.objects.get(id=iID)

            #Sanity check. No wiping other user's stickies (this should never happen)
            if Stickynote.objects.filter(id=iID, group_id__author_id=request.user.id).count() <= 0: return HttpResponseRedirect('') #FAILED

            pSticky.title = sTitle;
            pSticky.contents = sContents;
            pSticky.colour = Colour.objects.get(id=iColour);
            pSticky.group = Group.objects.get(id=iGroup);
            pSticky.shared = bShared;
            pSticky.last_edit_date = timezone.now()

            pSticky.save()
        else:
            #Does not yet exist: so we create a new one
            Stickynote.objects.create(title=sTitle, contents=sContents, created_date=timezone.now(), shared=bShared, colour_id=iColour, group_id=iGroup);
        return HttpResponseRedirect('/'); #SUCCESSFUL
    return HttpResponseRedirect('') #FAILED


#Delete a single sticky from the DB (with a given id)
def delete_sticky_by_id(request, *args, **kwargs):
    if request.user.is_authenticated:
        iID = request.POST.get('id', -1)
        #the given ID should actually exist and MUST be of the currently logged in user (no wiping other's stickies!)
        if Stickynote.objects.filter(id=iID,group_id__author_id=request.user.id).exists():
            Stickynote.objects.get(id=iID,group_id__author_id=request.user.id).delete();
            return HttpResponseRedirect('/'); #SUCCESSFUL
    return HttpResponseRedirect('') #FAILED


#get a random sticky colour from those in the DB and send it back via AJAX
def get_random_colour(request):
    pRandomColour = GetRandomColour();

    data = {
        'id':       pRandomColour.id,
        'name':     pRandomColour.name,
        'r':        pRandomColour.r,
        'g':        pRandomColour.g,
        'b':        pRandomColour.b,
        'a':        pRandomColour.a,
        'filename': pRandomColour.filename,
    }
    print(data)
    return JsonResponse(data)

'''
#Get all stickynote colours (and their RGB-values from the DB)
def retrieve_sticky_colours(request):
    #create an empty array
    colourlist = [];
    #populate it with the colournames
    for colour in Colour.objects.all().order_by('name'):
        colourlist.append([colour.id, colour.name.lower(), colour.r, colour.g, colour.b, colour.a/255]);
    print(colourlist)
    return JsonResponse({"colourlist": colourlist})
'''

#Check if the entered password and username are correct. If yes, login
def user_login(request, *args, **kwargs):
    username = request.POST.get('username', None)
    password = request.POST.get('password', None)

    if username and password and User.objects.filter(username__iexact=username).exists():

stickynote/templates/stickynote/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>StickyNote</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <!--Import Quill (a rich text editor) stylesheet-->
  <link href="https://cdn.quilljs.com/1.3.4/quill.snow.css" rel="stylesheet">
  <!--Import bootstrap-->
  <link href="{% static 'Bootstrap/bootstrap.min.css' %}" rel="stylesheet">

  <!-- To prevent favicon missing error -->
  <link rel="shortcut icon" href="">
<body>
  <!-- Navigation -->
  <nav id="id_navbar" class="navbar navbar-default navbar-static-top">
    <div class='container-fluid'>
      <div class="navbar-header">
        <div class="navbar-brand navbar-left">
      		<img id="id_stickynote_img" src="{% static 'Images/stickynote.png' %}"/>
      		<div>
      			<span id="id_stickynote_title">StickyNote</span>
      		</div>
        </div>
        <!--The icon that appears on mobile devices (when not enough space is available in the navbar for it all to fit)-->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!--
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li id="asdf" class="clickable"><a id="id_login_button" href="#">LOGIN</a></li>
        </ul>
      </div>
      -->
      <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      	{% with url_name=request.resolver_match.url_name %}
        <li{% if url_name == 'page_load' %} class="active"{% endif %}><a href="{% url 'stickynote:page_load' %}">Home</a></li>
        <li{% if url_name == 'friends_page' %} class="active"{% endif %}><a href="{% url 'friends:friends_page' %}">Friends</a></li>
        {% endwith %}
      </ul>


    <!-- Logout Form for new authentication system -->
		{% if user.is_authenticated %}
		<div class="nav navbar-nav navbar-right">
		  <div class="dropdown">
		   	<button class="btn btn-primary btn-lg dropdown-toggle" type="button" data-toggle="dropdown">Account
		    <span class="caret"></span></button>
		    <ul class="dropdown-menu">
		      <li><a href="#" class="show-login-name">Logged in as <strong>{{ user.username }}</strong></a></li>
		      <li><a href="{% url 'accounts:profile' %}">Show Profile</a></li>
		      <li>
		        <form method="POST" class="logout-button" action="{% url 'accounts:logout' %}" >
		          {% csrf_token %}
		          <button type="submit" class="btn btn-danger">Logout</button>
		        </form>
		      </li>
		    </ul>
		  </div>
		</div>
		{% endif %}

		<!-- Login Form for new authentication system -->
		{% if user.is_anonymous %}
		<div class="nav navbar-nav navbar-right">
		  <div class="dropdown">
		    <button class="btn btn-primary btn-lg dropdown-toggle" type="button" data-toggle="dropdown">Account
		    <span class="caret"></span></button>
		    <ul class="dropdown-menu">
		      <li><span class="show-login-name">Not logged in</span></li>
		      <li><a href="{% url 'accounts:login' %}">Log in</a></li>
		      <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
		    </ul>
		  </div>
		</div>
		{% endif %}
	  </div>
    </div>
  </nav>




  <!-- Login Form (old) -->
  <div id='id_dropdown_login' class='login-form hidden_elem'>
    <div class=''>
      <form id="id_login_form" method="POST">
        {% csrf_token %}
        <h4>Username</h4>
        <input name='username' placeholder="Username"/>
        <h4>Password</h4>
        <input name='password' type='password' placeholder="Password"/>
		        <p id="error_invalid_username_or_password" class="error_msg hidden_elem">ERROR: Invalid Username-Password Combination Given</p>
        <input class="submit_button clickable" type='submit' value='Sign In'/>
      </form>
    </div>
  </div>
  <!--Logout form (old)-->
  <div id="id_dropdown_logout" class='login-form hidden_elem'>
    <div class=''>
      <form id="id_logout_form">
        <h4 id="id_greeting_user">Hi USERNAME!</h4>
        <input class="submit_button clickable" type='submit' value='Log Out'/>
      </form>
    </div>
  </div>

  {% if messages %}
    <ul class="messages">
     {% for message in messages %}
      <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
     {% endfor %}
    </ul>
  {% endif %}

  {% block content %}
    {# variable content comes here #}
  {% endblock %}

  {% block JS %}
  	<!--Import JQuery-->
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  	<!--Import the Scrollbar appear-listener-->
  	<script src="{% static 'Scripts/scrollbar-resize-listener.js' %}"></script>
  	<!-- Include the Quill library -->
  	<script src="https://cdn.quilljs.com/1.3.4/quill.js"></script>
    <!--Import Bootstrap JS-->
    <script src="{% static 'Bootstrap/bootstrap.min.js' %}"></script>
  {% endblock JS %}
</body>

</html>