accounts/urls.py
from django.conf.urls import url
from . import views

app_name="accounts"

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^profile/edit', views.edit_profile, name='edit_profile'),
    url(r'^profile/', views.profile_view, name='profile'),
    url(r'^password/$', views.change_password, name='change_password'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('stickynote.urls')), #redirect every url to the homepage
    path('', include('accounts.urls')),
    path('', include('friends.urls')),

]

stickynote/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns #REST API

app_name = "stickynote"

urlpatterns = [
    path('', views.page_load, name='page_load'),
    path('set_sorting_pref_to_title', views.set_sorting_pref_to_title, name='set_sorting_pref_to_title'),
    path('set_sorting_pref_to_edited', views.set_sorting_pref_to_edited, name='set_sorting_pref_to_edited'),
    path('set_sorting_pref_to_created', views.set_sorting_pref_to_created, name='set_sorting_pref_to_created'),

    #TODO: OLD (to be removed probably)
    #path('ajax/retrieve_sticky_colours/', views.retrieve_sticky_colours, name='retrieve_sticky_colours'),
    #path('ajax/retrieve_current_user_data/', views.retrieve_current_user_data, name='retrieve_current_user_data'),
    #path('ajax/create_stickies/', views.create_stickies, name='create_stickies'),

    #UPDATED:
    path('ajax/get_sticky_by_id/', views.get_sticky_by_id, name='get_sticky_by_id'),
    path('ajax/set_or_create_sticky_by_id/', views.set_or_create_sticky_by_id, name='set_or_create_sticky_by_id'),
    path('ajax/delete_sticky_by_id/', views.delete_sticky_by_id, name='delete_sticky_by_id'),

    path('ajax/get_colour_by_id/', views.get_colour_by_id, name='get_colour_by_id'),
    path('ajax/get_random_colour/', views.get_random_colour, name='get_random_colour'),

    path('ajax/get_group_by_id/', views.get_group_by_id, name='get_group_by_id'),
    path('ajax/set_or_create_group_by_id/', views.set_or_create_group_by_id, name='set_or_create_group_by_id'),
    path('ajax/delete_group_by_id/', views.delete_group_by_id, name='delete_group_by_id'),

    path('ajax/user_is_authenticated/', views.user_is_authenticated, name='user_is_authenticated'),
    path('ajax/user_login/', views.user_login, name='user_login'),
    path('ajax/user_logout/', views.user_logout, name='user_logout'),

    #REST API
    path('stickies/', views.StickynoteList.as_view()),
    path('stickies/<int:id>/', views.StickynoteDetails.as_view()),
    path('stickies/user/<int:author_id>/', views.StickynoteAuthorList.as_view()),
    path('colours/', views.ColourList.as_view()),
    path('colours/<int:id>/', views.ColourDetails.as_view()),
    path('users/', views.UserList.as_view()),
    path('users/<int:id>', views.UserDetails.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class UpdateAccountForm(UserChangeForm):

    class Meta: 
        model = User
        fields = (
        'first_name',
        'last_name',
        'username',
        'password'
        )

    def clean_password(self):
    	return self.initial.get("password")

class FirstLastNameForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=100)
    last_name = forms.CharField(label='Last Name', max_length=100, required=False)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, UserChangeForm
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required #require users to be logged in to view page
from django.contrib import messages
from django.contrib.auth.models import User

from accounts.forms import UpdateAccountForm, FirstLastNameForm
from stickynote.models import Group, SortingPreference

# Create your views here.

def signup_view(request):
	if request.method == "POST":
		form = UserCreationForm(request.POST)
		formNames = FirstLastNameForm(request.POST)
		if form.is_valid():
			if formNames.is_valid():
				user = form.save(commit=False)
				user.first_name = formNames.cleaned_data['first_name']
				user.last_name = formNames.cleaned_data['last_name']
				user.save()
				# create a general, undeletable group to have a starting sticky
				group = Group.objects.create(title='General', author=user, shared = False, cannotBeDeleted = True)
				# log the user in here!
				login(request, user)
				return redirect('stickynote:page_load')
	else:
		form = UserCreationForm()
		formNames = FirstLastNameForm()
	return render(request, 'accounts/signup.html', {'form': form, 'formNames': formNames})

def login_view(request):
	if request.method == "POST":
		form= AuthenticationForm(data=request.POST)
		if form.is_valid():
			#log the user in here!
			user = form.get_user()
			login(request, user)
			return redirect('stickynote:page_load')
	else:
		form = AuthenticationForm()
	return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
	if request.method == "POST":
		logout(request)
		return redirect('stickynote:page_load')

def remove_view(request):
	if request.method == "POST":
		logout(request)
		return redirect('stickynote:page_load')

#Profile page
@login_required
def profile_view(request):
	sp = SortingPreference.objects.get(user=request.user)
	if not sp.sorting_pref == "":
		active_pref = sp.sorting_pref
	else:
		active_pref = "TITLE"
	print(active_pref)
	return render(request, 'accounts/profile.html', {'active_pref': active_pref})

#Change password
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

@login_required
def edit_profile(request):
    if request.method == "POST":
        form = UpdateAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('accounts:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = UpdateAccountForm(instance=request.user)
    return render(request, 'accounts/edit_profile.html', {'form': form})

accounts/templates/accounts/change_password.html
{% extends 'stickynote/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="content container">
    <div class="row">
        <div class="col-md-8 signup-wrapper">
			<form method="post">
			  {% csrf_token %}
			  {{ form }}
			  <button type="submit">Save changes</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'stickynote/base.html' %}

{% block content %}
<div class='signup-wrapper container'>
  <h1>Edit Profile</h1>
  <hr>
  <form method="POST" action="{% url 'accounts:edit_profile' %}" class="post-form">{% csrf_token %}
  	<div class="fieldWrapper">
  		{{ form.first_name.errors }}
      {{ form.first_name.label_tag }} <br/>
    	{{ form.first_name }}
    </div>

  	<div class="fieldWrapper">
  		{{ form.last_name.errors }}
      {{ form.last_name.label_tag }} <br/>
      {{ form.last_name }}
    </div>
    <div class="fieldWrapper">
      {{ form.username.errors }}
      {{ form.username.label_tag }} <br/>
      <div class='text-danger'>
        Warning: changing the username means changing the name you log in with!
      </div>
      {{ form.username }}
    </div>
    <div class='save-profile-edit'>
      <button type="submit" class="save btn btn-default">Save</button>
    </div>
  </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'stickynote/base.html' %}

{% block content %}
<div class="content container">
    <div class="row">
        <div class="signup-wrapper">
	        <h1>Log in</h1>
		    <div class='redirect-to-signup'>
		    	<p>Don't have an account yet? <a href="{% url 'accounts:signup' %}">Sign up now!</a></p>
		    </div>
	        <hr>
		    <form method="POST" class="login-form-new" >{% csrf_token %}
		        {{ form }}
		        <button type="submit" class="save btn btn-default">Login</button>
		    </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'stickynote/base.html' %}
{% load staticfiles %}

{% block content %}
<div class='signup-wrapper container'>
	<h1>Profile of user <span class='profile-username'><strong>{{ request.user.username }}</strong></span></h1>
	<hr>
	<div class='current-first-name'>
      <span class='profile-title'>First Name:</span> &emsp;
      {% if request.user.first_name|length > 0 %}
	    {{ request.user.first_name }}
	  {% else %}
	    <i>first name is not set</i>
	  {% endif %}
    </div>
	
	<div class='current-last-name'>
	  <span class='profile-title'>Last Name:</span> &emsp;
	  {% if request.user.last_name|length > 0 %}
	    {{ request.user.last_name }}
	  {% else %}
	    <i>last name is not set</i>
	  {% endif %}
	</div>
	<div class='edit-profile'>
		<a class="btn btn-primary" id='edit-profile-button' href="{% url 'accounts:edit_profile' %}">Edit Profile  <span class="glyphicon glyphicon-pencil"></span></a>
		<a class="btn btn-danger" id='change-password-button' href="{% url 'accounts:change_password' %}">Change Password</a>
	</div>
	<div class='set-sorting-preference'>
		<h2>Set sorting preference</h2>
		<form method="POST" class="sorting-to-TITLE" action="{% url 'stickynote:set_sorting_pref_to_title' %}" >
    		{% csrf_token %}
    		<button type="submit" class='btn btn-{% if active_pref == "TITLE" %}success{% else %}info{% endif %}' aria-hidden='true'>Title</button>
    	</form>
    	<form method="POST" class="sorting-to-CREATED" action="{% url 'stickynote:set_sorting_pref_to_created' %}" >
    		{% csrf_token %}
    		<button type="submit" class='btn btn-{% if active_pref == "DATE_CREATED" %}success{% else %}info{% endif %}' aria-hidden='true'>Date Created</button>
    	</form>
    	<form method="POST" class="sorting-to-EDITED" action="{% url 'stickynote:set_sorting_pref_to_edited' %}" >
    		{% csrf_token %}
    		<button type="submit" class='btn btn-{% if active_pref == "DATE_EDITED" %}success{% else %}info{% endif %}' aria-hidden='true'>Last Edit</button>
    	</form>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'stickynote/base.html' %}

{% block content %}
<div class="content container">
    <div class="row">
        <div class="signup-wrapper">
		    <h1>Sign up</h1>
		    <div class='redirect-to-login'>
		    	<p>Already have an account? <a href="{% url 'accounts:login' %}">Log in here!</a></p>
		    </div>
		    <hr>
		    <form method="POST" class="signup-form" >{% csrf_token %}
		    	<div class="fieldWrapper">
			        {{ form.username.errors }}
			        {{ form.username.label_tag }}*
			        <br/>
			        {{ form.username }}
		        </div>
		        <div class="fieldWrapper">
		        	<ul class="signup-req">
			        	<li>150 characters or fewer. Letters, digits and @/./+/-/_ only.</li>
					</ul>
			    </div>
		        <div class="fieldWrapper">
			        {{ form.password1.errors }}
			        {{ form.password1.label_tag }}*
			        <br/>
			        {{ form.password1 }}
			    </div>
		        <div class="fieldWrapper">
			        <ul class="signup-req">
			        	<li>Your password can't be too similar to your other personal information.</li>
						<li>Your password must contain at least 8 characters.</li>
						<li>Your password can't be a commonly used password.</li>
						<li>Your password can't be entirely numeric.</li>
					</ul>
				</div>
				<div class="fieldWrapper">
			        {{ form.password2.errors }}
			        {{ form.password2.label_tag }}*
			        <br/>
			        {{ form.password2 }}
			    </div>

			    <div class="fieldWrapper-extraspace">
			        {{ formNames.first_name.errors }}
			        {{ formNames.first_name.label_tag }}*
			        <br/>
			        {{ formNames.first_name }}
		        </div>

		        <div class="fieldWrapper">
			        {{ formNames.last_name.errors }}
			        {{ formNames.last_name.label_tag }}
			        <br/>
			        {{ formNames.last_name }}
		        </div>
		        <button type="submit" class="save btn btn-default">Signup</button>
		    </form>
		</div>
    </div>
</div>
{% endblock %}